<?php
session_start();
require_once('../Connections/paymaster.php');
require __DIR__ . '/../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Check for user authentication
if (!isset($_SESSION['SESS_MEMBER_ID']) || trim($_SESSION['SESS_MEMBER_ID']) == '') {
    http_response_code(401);
    echo 'Unauthorized access';
    exit;
}

// Retrieve POST parameters
$period = filter_input(INPUT_POST, 'period', FILTER_SANITIZE_FULL_SPECIAL_CHARS) ?: -1;
$month = filter_input(INPUT_POST, 'period_text', FILTER_SANITIZE_FULL_SPECIAL_CHARS) ?: 'Unknown Period';
// Note: 'bank' parameter is not used in this script but is included in the AJAX call; we can ignore it

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();

// Set document properties
$spreadsheet->getProperties()
    ->setCreator($_SESSION['SESS_FIRST_NAME'])
    ->setTitle('Employee Report')
    ->setSubject('Detailed Employee Report for ' . $month);

// Add header text (like in the PDF)
$sheet->setCellValue('A1', 'OLABISI ONABANJO UNIVERSITY TEACHING HOSPITAL');
$sheet->setCellValue('A2', 'Employee Report for the Month of: ' . $month);

// Merge cells for the header text to center it across columns
$sheet->mergeCells('A1:K1');
$sheet->mergeCells('A2:K2');

// Style the header
$sheet->getStyle('A1')->getFont()->setBold(true)->setSize(12);
$sheet->getStyle('A2')->getFont()->setSize(10);
$sheet->getStyle('A1:K1')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);
$sheet->getStyle('A2:K2')->getAlignment()->setHorizontal(\PhpOffice\PhpSpreadsheet\Style\Alignment::HORIZONTAL_CENTER);

// Add table headers (starting from row 4)
$headers = [
    'S/No',
    'Staff No.',
    'Name',
    'Email',
    'Dept',
    'Emp Date',
    'Post',
    'Grade',
    'Step',
    'Bank',
    'Acct. No.'
];
$sheet->fromArray($headers, null, 'A4');

// Style the table headers
$sheet->getStyle('A4:K4')->getFont()->setBold(true);
$sheet->getStyle('A4:K4')->getFill()
    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
    ->getStartColor()->setRGB('D3D3D3'); // Light gray background, matching the PDF

// Fetch data
try {
    $sql = 'SELECT master_staff.staff_id, master_staff.`NAME`, tbl_dept.dept, master_staff.GRADE, master_staff.STEP, 
            tbl_bank.BNAME, master_staff.ACCTNO, employee.EMPDATE, employee.EMAIL, employee.POST
            FROM master_staff
            INNER JOIN tbl_dept ON master_staff.DEPTCD = tbl_dept.dept_id
            INNER JOIN tbl_bank ON master_staff.BCODE = tbl_bank.BCODE
            INNER JOIN employee ON master_staff.staff_id = employee.staff_id 
            WHERE master_staff.period = ?';
    $query = $conn->prepare($sql);
    $query->execute([$period]);
    $res = $query->fetchAll(PDO::FETCH_ASSOC);

    // Add data rows starting from row 5
    $row = 5;
    $counter = 1;
    foreach ($res as $link) {
        $data = [
            $counter,
            $link['staff_id'] ?? '',
            $link['NAME'] ?? '',
            $link['EMAIL'] ?? '',
            $link['dept'] ?? '',
            $link['EMPDATE'] ?? '',
            $link['POST'] ?? '',
            $link['GRADE'] ?? '',
            $link['STEP'] ?? '',
            $link['BNAME'] ?? '',
            $link['ACCTNO'] ?? ''
        ];
        $sheet->fromArray($data, null, 'A' . $row);
        $row++;
        $counter++;
    }

    // Add borders to the table
    $tableRange = 'A4:K' . ($row - 1);
    $sheet->getStyle($tableRange)->getBorders()->getAllBorders()
        ->setBorderStyle(\PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN);

    // Auto-size columns for better readability
    foreach (range('A', 'K') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }

} catch (PDOException $e) {
    http_response_code(500);
    echo 'Error: ' . $e->getMessage();
    exit;
}

// Add footer with printed date
$printedDate = date('l, F d, Y'); // e.g., "Saturday, May 10, 2025"
$footerRow = $row + 1;
$sheet->setCellValue('A' . $footerRow, "Report Generated by: {$_SESSION['SESS_FIRST_NAME']} | Printed on: {$printedDate}");
$sheet->mergeCells('A' . $footerRow . ':K' . $footerRow);

// Generate the Excel file and encode it as base64
ob_start();
$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
$excelOutput = ob_get_clean();
$base64 = base64_encode($excelOutput);

// Return the base64-encoded string as the AJAX response
echo $base64;
exit;