<?php
session_start();

include_once('../classes/model.php');
require_once('../Connections/paymaster.php');
if (!isset($_SESSION['SESS_MEMBER_ID']) || (trim($_SESSION['SESS_MEMBER_ID']) == '')) {
	header("location: ../index.php");
	exit();
}



?>
<!DOCTYPE html>
<?php include('../header1.php'); ?>

<body data-color="grey" class="flat">

	<div class="modal fade hidden-print" id="myModal"></div>
	<div id="wrapper">
		<div id="header" class="hidden-print">
			<h1><a href="../index.php"><img src="img/header_logo.png" class="hidden-print header-log" id="header-logo" alt=""></a></h1>
			<a id="menu-trigger" href="#"><i class="fa fa-bars fa fa-2x"></i></a>
			<div class="clear"></div>
		</div>




		<div id="user-nav" class="hidden-print hidden-xs">
			<ul class="btn-group ">
				<li class="btn  hidden-xs"><a title="" href="switch_user" data-toggle="modal" data-target="#myModal"><i class="icon fa fa-user fa-2x"></i> <span class="text"> Welcome <b> <?php echo $_SESSION['SESS_FIRST_NAME']; ?> </b></span></a></li>
				<li class="btn  hidden-xs disabled">
					<a title="" href="/" onclick="return false;"><i class="icon fa fa-clock-o fa-2x"></i> <span class="text">
							<?php
							$Today = date('y:m:d', time());
							$new = date('l, F d, Y', strtotime($Today));
							echo $new;
							?> </span></a>
				</li>
				<li class="btn "><a href="#"><i class="icon fa fa-cog"></i><span class="text">Settings</span></a></li>
				<li class="btn  ">
					<a href="index.php"><i class="fa fa-power-off"></i><span class="text">Logout</span></a>
				</li>
			</ul>
		</div>
		<?php include("report_sidebar.php"); ?>



		<div id="content" class="clearfix sales_content_minibar">

			<div id="content-header" class="hidden-print">
				<h1><i class="fa fa-beaker"></i> Report Input</h1> <span id="ajax-loader"><img src="img/ajax-loader.gif" alt="" /></span>
			</div>

			<div id="breadcrumb" class="hidden-print">
				<a href="../home.php"><i class="fa fa-home"></i> Dashboard</a><a href="index.php">Reports</a><a class="current" href="tax_returns.php">Report Input: Detailed Tax Returns</a>
			</div>
			<div class="clear"></div>
			<div class="row">
				<div class="col-md-12">
					<div class="widget-box">
						<div class="widget-title">
							<span class="icon">
								<i class="fa fa-align-justify"></i>
							</span>
							<h5 align="center"></h5>
							<div class="clear"></div>
							<div class="clear"></div>

						</div>
						<div class="row">

							<div class="col-md-12 pull-left">
								<h3 style="text-transform: uppercase;" class="inline-block text-center"><img src="img/oouth_logo.gif" width="10%" height="10%" class="header-log" id="header-logo" alt="">
									OLABISI ONABANJO UNIVERSITY TEACHING HOSPITAL
								</h3>
							</div>
							<div class="col-md-12 hidden-print">
								<form class="form-horizontal form-horizontal-mobiles" method="POST" id="downloadForm">
									<div class="form-group">
										<label for="period" class="col-sm-3 col-md-3 col-lg-2 control-label hidden-print">Pay Period :</label>
										<div class="col-sm-9 col-md-9 col-lg-10">&nbsp;
											<div class="input-group">
												<span class="input-group-addon"><i class="fa fa-location-arrow hidden-print"></i></span>
                                                <select id="period" name="period" class="form-control hidden-print">
                                                    <!-- Options will be populated dynamically using jQuery -->
                                                </select>
											</div>
										</div>

									</div>

									<div class="form-actions">
										<button name="generate_report" type="submit" id="generate_report" class="btn btn-primary submit_button btn-large hidden-print">Download Excel</button>
									</div>
								</form>
							</div>
						</div>
			</div>

		</div>


		<div id="footer" class="col-md-12">
			<div class="col-md-12">
				Report Generated by :<?php echo $_SESSION['SESS_FIRST_NAME']; ?> on <?php $Today = date('y:m:d', time());
																					$new = date('l, F d, Y', strtotime($Today));
																					echo $new; ?>
			</div>
			<div class="hidden-print"> Please visit our <a href="http://www.oouth.com/" target="_blank">
					website </a>
				to learn the latest information about the project.
				<span class="text-info"> <span class="label label-info"> 14.1</span></span>
			</div>
		</div>

	</div><!--end #content-->
	<!--end #wrapper-->

    <script>
        $(document).ready(function() {
            // Fetch periods from the server and populate the dropdown
            $.ajax({
                url: 'get_periods.php',
                method: 'GET',
                dataType: 'json',
                success: function(data) {
                    var options = '';
                    data.forEach(function(period) {
                        options += `<option value="${period.periodId}">${period.periodText}</option>`;
                    });
                    $('#period').html(options);
                }
            });

            // Handle form submission
            $('#downloadForm').on('submit', function(e) {
                e.preventDefault();
                var periodId = $('#period').val();

                $.ajax({
                    url: 'generate_excel.php',
                    method: 'POST',
                    data: {
                        periodId: periodId
                    },
                    success: function(response) {
                        window.location.href = 'generate_excel.php?periodId=' + periodId;
                    }
                });
            });
        });
    </script>
	<script src="js/main.js"></script>
</body>

</html>