<?php
session_start();
require_once('../Connections/paymaster.php');
require __DIR__.'/../vendor/autoload.php';
$tcpdf_path = __DIR__ . '/../vendor/tecnickcom/tcpdf/tcpdf.php';
if (!file_exists($tcpdf_path)) { http_response_code(500); exit('TCPDF not found'); }
require_once $tcpdf_path;

if (!isset($_SESSION['SESS_MEMBER_ID']) || trim($_SESSION['SESS_MEMBER_ID']) == '') { header('HTTP/1.1 401 Unauthorized'); exit('Unauthorized'); }

$periodFrom = filter_input(INPUT_POST, 'periodFrom', FILTER_SANITIZE_FULL_SPECIAL_CHARS) ?: -1;
$periodTo = filter_input(INPUT_POST, 'periodTo', FILTER_SANITIZE_FULL_SPECIAL_CHARS) ?: -1;
$title = filter_input(INPUT_POST, 'title', FILTER_SANITIZE_FULL_SPECIAL_CHARS) ?: 'Variance Report';
if ($periodFrom == -1 || $periodTo == -1) { header('HTTP/1.1 400 Bad Request'); exit('Missing parameters'); }

function getPeriodText(PDO $conn, $periodId) {
    try { $q = $conn->prepare('SELECT description, periodYear FROM payperiods WHERE periodId = ?'); $q->execute([$periodId]); $r = $q->fetch(PDO::FETCH_ASSOC); return $r ? ($r['description'] . '-' . $r['periodYear']) : ''; } catch (PDOException $e) { return ''; }
}
$fromText = getPeriodText($conn, $periodFrom);
$toText = getPeriodText($conn, $periodTo);

try {
    $q = $conn->prepare('SELECT staff_id, ANY_VALUE(master_staff.`NAME`) AS `NAME` FROM master_staff WHERE period = ? UNION SELECT staff_id, ANY_VALUE(master_staff.`NAME`) AS `NAME` FROM master_staff WHERE period = ? ORDER BY staff_id');
    $q->execute([$periodTo, $periodFrom]);
    $rows = $q->fetchAll(PDO::FETCH_ASSOC);
} catch (PDOException $e) { header('HTTP/1.1 500 Internal Server Error'); exit('DB error'); }

function varianceAmount(PDO $conn, $periodId, $staffId) {
    try {
        $query = $conn->prepare('SELECT tbl_master.period,
       SUM(tbl_master.allow) as amount
FROM tbl_master
INNER JOIN employee ON employee.staff_id = tbl_master.staff_id
RIGHT JOIN tbl_earning_deduction ON tbl_earning_deduction.ed_id = tbl_master.allow_id
INNER JOIN tbl_dept ON tbl_dept.dept_id = employee.DEPTCD
INNER JOIN payperiods ON payperiods.periodId = tbl_master.period
WHERE tbl_master.period = ? 
AND employee.staff_id = ?
GROUP BY employee.staff_id');
        $res = $query->execute(array($periodId, $staffId));
        if ($row = $query->fetch()) {
            return (float)$row['amount'];
        } else {
            return 0.0;
        }
    } catch (PDOException $e) {
        return 0.0;
    }
}

$pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
$pdf->setPrintHeader(false); $pdf->setPrintFooter(false);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 9);

$header1 = 'OLABISI ONABANJO UNIVERSITY TEACHING HOSPITAL';
$header2 = 'Payroll Variance Between the Month of ' . $fromText . ' AND ' . $toText;
$pdf->SetFont('helvetica', 'B', 11); $pdf->Cell(0, 6, $header1, 0, 1, 'C');
$pdf->SetFont('helvetica', '', 10); $pdf->Cell(0, 6, $header2, 0, 1, 'C');
$pdf->Ln(2);

$html = '<table border="1" cellpadding="4" width="100%">'
    . '<thead><tr style="background-color:#eef2ff;">'
    . '<th width="10%"><b>S/N</b></th>'
    . '<th width="15%"><b>Staff No</b></th>'
    . '<th width="35%"><b>Name</b></th>'
    . '<th width="15%"><b>' . htmlspecialchars($fromText) . '</b></th>'
    . '<th width="15%"><b>' . htmlspecialchars($toText) . '</b></th>'
    . '<th width="10%"><b>Variance</b></th>'
    . '</tr></thead><tbody>';

$sn = 1; $sumCurrent = 0; $sumPrevious = 0;
foreach ($rows as $r) {
    $current = varianceAmount($conn, $periodFrom, $r['staff_id']);
    $previous = varianceAmount($conn, $periodTo, $r['staff_id']);
    $variance = $current - $previous;
    $html .= '<tr>'
        . '<td width="10%">' . $sn . '</td>'
        . '<td width="15%">' . htmlspecialchars($r['staff_id'] ?? '') . '</td>'
        . '<td width="35%">' . htmlspecialchars($r['NAME'] ?? '') . '</td>'
        . '<td width="15%">₦' . number_format($current) . '</td>'
        . '<td width="15%">₦' . number_format($previous) . '</td>'
        . '<td width="10%">₦' . number_format($variance) . '</td>'
        . '</tr>';
    $sumCurrent += $current; $sumPrevious += $previous; $sn++;
}
$totalVariance = $sumCurrent - $sumPrevious;
$html .= '<tr>'
    . '<td colspan="3"><b>TOTAL</b></td>'
    . '<td><b>₦' . number_format($sumCurrent) . '</b></td>'
    . '<td><b>₦' . number_format($sumPrevious) . '</b></td>'
    . '<td><b>₦' . number_format($totalVariance) . '</b></td>'
    . '</tr>';
$html .= '</tbody></table>';

$pdf->writeHTML($html, true, false, true, false, '');

$printedDate = date('l, F d, Y');
$pdf->Ln(2);
$pdf->Cell(0, 6, 'Report Generated by: ' . ($_SESSION['SESS_FIRST_NAME'] ?? 'User') . ' | Printed on: ' . $printedDate, 0, 1, 'L');

$pdf->Output('Variance_Report_' . $fromText . '_vs_' . $toText . '.pdf', 'D');
?>